server:
  port: ${NOTIFICATION_SERVICE_APP_PORT}

spring:
  sql:
    init:
      mode: never

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

jwt:
  secret: ${JWT_SECRET_KEY}

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  message-service-id: ${TWILIO_MESSAGE_SERVICE_ID}