server:
  port: ${NOTIFICATION_SERVICE_APP_PORT}

spring:
  datasource:
    url: jdbc:postgresql://${NOTIFICATION_SERVICE_DB_HOST}:${NOTIFICATION_SERVICE_DB_PORT}/fc-notification-service
    username: ${NOTIFICATION_SERVICE_DB_USER}
    password: ${NOTIFICATION_SERVICE_DB_PASS}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    table: flyway_schema_history
    clean-disabled: true
    out-of-order: false

  sql:
    init:
      mode: never

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

jwt:
  secret: ${JWT_SECRET_KEY}